"""Downstream task evaluation (synthetic-data augmentation utility).

The package houses regressors / segmentors that consume real + synthetic
volumes generated by the trained VAE+diffusion stack. Each subtask follows
the MAISI paradigm: train on real-only, real+synth, and synth-only, then
report the delta on a fixed real test set.
"""
